// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqHNT6lZpvFOh3xyEJA8WFtIVfCVX1rQ0',
    appId: '1:836976921245:web:d5a99de60462dc0775a274',
    messagingSenderId: '836976921245',
    projectId: 'flutterapitask-ed2b1',
    authDomain: 'flutterapitask-ed2b1.firebaseapp.com',
    storageBucket: 'flutterapitask-ed2b1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC107xzSlZYDm6otsCT_zFTmN-7nuoMoKU',
    appId: '1:836976921245:android:6efbf696a8ce2bca75a274',
    messagingSenderId: '836976921245',
    projectId: 'flutterapitask-ed2b1',
    storageBucket: 'flutterapitask-ed2b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWUAj0IMA_hRnO3T-n56MoUwOl7b61KWk',
    appId: '1:836976921245:ios:ee346afb7ea3027c75a274',
    messagingSenderId: '836976921245',
    projectId: 'flutterapitask-ed2b1',
    storageBucket: 'flutterapitask-ed2b1.appspot.com',
    iosBundleId: 'com.example.flutterApiTaskCleanArchitecture',
  );
}
